原文： http://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html

Translator: 陳胤泰 YinTaiChen

# Pytorch是什麼?

它是個基於 Python 的科學運算套件，是為了以下兩種需求設計的：

* 為了使用 GPU 的運算能力，替代 numpy

* 深度學習的研究平台，提供極高的彈性與速度

# 暖身

# 張量(Tensor)

張量與 numpy 的 ndarrays 十分相似，除此之外，張量可以在 GPU 中使用來加速運算。

In [1]:
from __future__ import print_function
import torch

建構一個 5x3、未初始化的矩陣：

In [2]:
x = torch.Tensor(5, 3)
print(x)


1.00000e-08 *
  0.0000  0.0000  0.0000
  0.0000  0.0000  0.0000
  0.0000  0.0000  0.0000
  0.0000  1.2726  0.0000
  1.2386  0.0000  0.0000
[torch.FloatTensor of size 5x3]



建構一個隨機初始化的矩陣：

In [3]:
x = torch.rand(5, 3)
print(x)


 0.0458  0.9463  0.3023
 0.7245  0.5622  0.4638
 0.6281  0.4453  0.6268
 0.6360  0.8683  0.2956
 0.4382  0.5706  0.0589
[torch.FloatTensor of size 5x3]



取得它的大小：

In [4]:
print(x.size())

torch.Size([5, 3])


torch.Size 事實上是個元組 (tuple)，所以它支援相同的運算。

# 運算

運算的語法 (Syntax) 十分多樣。讓我們以加法為例：

加法： 語法一

In [5]:
y = torch.rand(5, 3)
print(x + y)


 0.1158  1.2546  1.0759
 1.5268  1.3263  1.4369
 1.2263  1.1830  1.5572
 1.3834  0.9291  1.2139
 0.8003  0.7701  0.6754
[torch.FloatTensor of size 5x3]



加法： 語法二

In [6]:
print(torch.add(x, y))


 0.1158  1.2546  1.0759
 1.5268  1.3263  1.4369
 1.2263  1.1830  1.5572
 1.3834  0.9291  1.2139
 0.8003  0.7701  0.6754
[torch.FloatTensor of size 5x3]



加法： 給定一個輸出張量

In [7]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)


 0.1158  1.2546  1.0759
 1.5268  1.3263  1.4369
 1.2263  1.1830  1.5572
 1.3834  0.9291  1.2139
 0.8003  0.7701  0.6754
[torch.FloatTensor of size 5x3]



加法： 原地(改變原本的張量)

In [8]:
# adds x to y
y.add_(x)
print(y)


 0.1158  1.2546  1.0759
 1.5268  1.3263  1.4369
 1.2263  1.1830  1.5572
 1.3834  0.9291  1.2139
 0.8003  0.7701  0.6754
[torch.FloatTensor of size 5x3]



任何會改變原本張量的運算，其後都有底線 _ 。
舉例來說：x.copy_(y), 以及 x.t_() 這兩個運算都會改變 x。

你可以使用像是 numpy 標準的索引方法，或是各式各樣花俏的索引方法。

In [9]:
print(x[:, 1])


 0.9463
 0.5622
 0.4453
 0.8683
 0.5706
[torch.FloatTensor of size 5]



# 與 Numpy 的銜接

將張量轉換為 numpy 的陣列，或反之，是件輕而易舉的事情。

張量與 numpy 陣列會共享記憶體位址，改變其中一個便會改變另一個。

# 將張量轉換為 numpy 陣列

In [10]:
a = torch.ones(5)
print(a)


 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]



In [11]:
b = a.numpy()
print(b)

[ 1.  1.  1.  1.  1.]


看看 numpy 陣列的值如何改變。

In [12]:
a.add_(1)
print(a)
print(b)


 2
 2
 2
 2
 2
[torch.FloatTensor of size 5]

[ 2.  2.  2.  2.  2.]


# 將 numpy 陣列轉換為張量

看看改變 numpy 陣列如何自動改變張量。

In [13]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[ 2.  2.  2.  2.  2.]

 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]



除了 CharTensor 以外，所有位於 CPU 的張量皆支援與 numpy 陣列之間的來回轉換。

# CUDA 張量

藉由使用 .cuda 函式，可將張量移到 GPU。

In [14]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    x + y